function out1 = inertiaFcn(q1,in2)
%inertiaFcn
%    OUT1 = inertiaFcn(Q1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    12-Feb-2024 17:10:09

I1 = in2(1,:);
m1 = in2(2,:);
out1 = I1+m1./4.0;
