function out1 = jacobDotFcn(q1,Dq1)
%jacobDotFcn
%    OUT1 = jacobDotFcn(Q1,Dq1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:12

t2 = Dq1.^2;
out1 = [-t2.*cos(q1);-t2.*sin(q1);0.0;0.0;0.0;0.0];
