function out1 = jacobFcn(q1)
%jacobFcn
%    OUT1 = jacobFcn(Q1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:12

out1 = [-sin(q1);0.0;cos(q1);0.0;-1.0;0.0];
