function regressor = regressorFcn(q1,Dq1,DDq1)
%regressorFcn
%    REGRESSOR = regressorFcn(Q1,Dq1,DDq1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:11

%dynamic parameters:   I1 m1 
regressor = [DDq1,DDq1./4.0+cos(q1).*(9.81e+2./2.0e+2)];
