function out1 = inertiaSimulation(in1,payload)
%inertiaSimulation
%    OUT1 = inertiaSimulation(IN1,PAYLOAD)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:26

ql2 = in1(2,:);
ql3 = in1(3,:);
t2 = cos(ql2);
t3 = cos(ql3);
t4 = sin(ql2);
t5 = sin(ql3);
t8 = payload+1.1e+1;
t14 = payload./8.0e+1;
t6 = t3.^2;
t7 = t5.*2.0;
t9 = t3.*1.0e+1;
t10 = t3./4.0;
t11 = t5./2.0;
t12 = t3./1.0e+1;
t17 = t14+1.1e+1./8.0e+1;
t13 = -t11;
t15 = t10+1.0./2.0;
t16 = t7+t9+5.0;
t18 = t12+t13;
t19 = -t5.*t8.*t15.*(t11-t12);
t20 = t5.*t8.*t15.*(t11-t12);
mt1 = [payload./2.0+t2.*(1.7e+1./2.0)+t3.*(1.1e+1./4.0)+t6.*(1.1e+1./1.6e+1)+(payload.*t2)./2.0+(payload.*t6)./1.6e+1+payload.*t10+t2.*t3.*(1.1e+1./4.0)+payload.*t2.*t10+4.11e+2./4.0e+1,t20+(t2.*(t8.*t15+3.0))./2.0+t3.*((t8.*t15)./4.0+t8.*t15.*(t3./2.0+t5./1.0e+1))+3.0./4.0,t4.*t5.*(payload./4.0+1.1e+1./4.0).*(-1.0./2.0),0.0,0.0,0.0,t2.*(3.0./2.0)+t3.*t16.*t17.*(t2.*2.0+t3+2.0)+t5.*t8.*(t2./2.0+t15).*(t11-t12)+3.0./4.0,t20+t3.*t16.*t17.*(t3+2.0)+3.0./4.0,0.0,0.0,0.0,0.0,t4.*t5.*t8.*(-1.0./8.0),0.0,payload./1.6e+1+7.1e+1./8.0e+1,0.0,0.0,0.0,0.0,0.0,0.0];
mt2 = [1.674466340379727e+1,0.0,0.0,0.0,0.0,0.0,0.0,4.856207320063636,0.0,0.0,0.0,0.0,0.0,0.0,4.97e+2./8.0e+2];
out1 = reshape([mt1,mt2],6,6);
