function out1 = initialStateSimulation
%initialStateSimulation
%    OUT1 = initialStateSimulation

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:28

t2 = pi./2.0;
out1 = [0.0;t2;0.0;-2.7468e-5;t2;0.0];
