function out1 = initialTauSimulation
%initialTauSimulation
%    OUT1 = initialTauSimulation

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:28

out1 = [1.3734e+2;0.0;0.0];
