function out1 = inverseDynamicsNonLinearFcn(in1,in2,payload)
%inverseDynamicsNonLinearFcn
%    OUT1 = inverseDynamicsNonLinearFcn(IN1,IN2,PAYLOAD)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:27

Dql1 = in2(1,:);
Dql2 = in2(2,:);
Dql3 = in2(3,:);
Dqm1 = in2(4,:);
Dqm2 = in2(5,:);
Dqm3 = in2(6,:);
ql1 = in1(1,:);
ql2 = in1(2,:);
ql3 = in1(3,:);
qm1 = in1(4,:);
qm2 = in1(5,:);
qm3 = in1(6,:);
t2 = cos(ql1);
t3 = cos(ql2);
t4 = cos(ql3);
t5 = sin(ql1);
t6 = sin(ql2);
t7 = sin(ql3);
t8 = Dql1.^2;
t9 = Dql2.^2;
t10 = Dql3.^2;
t11 = ql3.*2.0;
t12 = Dql1+Dql2;
t14 = payload+1.1e+1;
t15 = Dql3.*1.5e+3;
t16 = Dqm3.*1.5e+3;
t17 = Dql1.*2.0e+3;
t18 = Dql2.*2.1e+3;
t19 = Dqm1.*2.0e+3;
t20 = Dqm2.*2.1e+3;
t23 = ql3.*3.0e+6;
t24 = qm3.*3.0e+6;
t25 = ql2.*4.0e+6;
t26 = qm2.*4.0e+6;
t27 = ql1.*5.0e+6;
t28 = qm1.*5.0e+6;
t13 = sin(t11);
t21 = t8./2.0;
t29 = (Dql3.*t7.*t12)./2.0;
t30 = t5.*(9.81e+2./1.0e+2);
t31 = t2.*t3.*(9.81e+2./1.0e+2);
t22 = -t21;
t32 = -t31;
t33 = t22+t30;
t34 = t6.*t33;
t35 = t29+t32+t34;
et1 = t2.*1.3734e+2+t17-t19+t27-t28+payload.*t2.*(9.81e+2./2.0e+2)+t2.*t3.*8.3385e+1-t5.*t6.*8.3385e+1-t6.*t9.*(1.7e+1./4.0)-Dql1.*Dql2.*t6.*(1.7e+1./2.0)-Dql1.*Dql3.*t7.*(1.1e+1./4.0)-Dql2.*Dql3.*t7.*(1.1e+1./4.0)-Dql1.*Dql3.*t13.*(1.1e+1./1.6e+1)-Dql2.*Dql3.*t13.*(1.1e+1./1.6e+1)+payload.*t2.*t3.*(9.81e+2./2.0e+2)-payload.*t5.*t6.*(9.81e+2./2.0e+2)-(payload.*t6.*t9)./4.0+t2.*t3.*t4.*2.69775e+1-t4.*t5.*t6.*2.69775e+1-t4.*t6.*t9.*(1.1e+1./8.0)-t4.*t6.*t10.*(1.1e+1./8.0);
et2 = payload.*t2.*t3.*t4.*(9.81e+2./4.0e+2)-payload.*t4.*t5.*t6.*(9.81e+2./4.0e+2)-(payload.*t4.*t6.*t9)./8.0-(payload.*t4.*t6.*t10)./8.0-(Dql1.*Dql2.*payload.*t6)./2.0-(Dql1.*Dql3.*payload.*t7)./4.0-(Dql2.*Dql3.*payload.*t7)./4.0-(Dql1.*Dql3.*payload.*t13)./1.6e+1-(Dql2.*Dql3.*payload.*t13)./1.6e+1-Dql1.*Dql2.*t4.*t6.*(1.1e+1./4.0)-Dql1.*Dql3.*t3.*t7.*(1.1e+1./4.0)-Dql2.*Dql3.*t3.*t7.*(1.1e+1./4.0)-(Dql1.*Dql2.*payload.*t4.*t6)./4.0-(Dql1.*Dql3.*payload.*t3.*t7)./4.0-(Dql2.*Dql3.*payload.*t3.*t7)./4.0;
out1 = [et1+et2;t18-t20+t25-t26-t34.*3.0+t7.*(t14.*t35.*(t4./1.0e+1-t7./2.0)+(Dql3.*t4.*t12)./5.0)+t2.*t3.*2.943e+1-t4.*((t14.*t35)./4.0+t14.*t35.*(t4./2.0+t7./1.0e+1)+(Dql3.*t7.*t12)./5.0);t15-t16+t23-t24+(payload./4.0+1.1e+1./4.0).*((t12.^2.*t13)./8.0+t7.*(t9./2.0+t21-sin(ql1+ql2).*(9.81e+2./1.0e+2)+t3.*t21+Dql1.*Dql2));-t17+t19-t27+t28;-t18+t20-t25+t26;-t15+t16-t23+t24];
