function out1 = noiseSimulation
%noiseSimulation
%    OUT1 = noiseSimulation

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:28

out1 = [1.0e-5;1.0e-4];
