function out1 = uMaxSimulation
%uMaxSimulation
%    OUT1 = uMaxSimulation

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:28

out1 = [1.0e+3;8.7e+2;5.0e+2];
