function [K,D,Im,V,C,umax,x0,noise,u0] = dataSimulation
%dataSimulation
%    [K,D,Im,V,C,UMAX,X0,NOISE,U0] = dataSimulation

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    12-Feb-2025 22:38:58

K = reshape([5.0e+6,0.0,0.0,4.0e+6],[2,2]);
if nargout > 1
    D = reshape([2.0e+3,0.0,0.0,2.1e+3],[2,2]);
end
if nargout > 2
    Im = reshape([1.0745,0.0,0.0,2.1e+1./5.0e+1],[2,2]);
end
if nargout > 3
    V = reshape([3.0,0.0,0.0,3.0],[2,2]);
end
if nargout > 4
    C = [5.0,5.0];
end
if nargout > 5
    umax = [4.6e+1;2.3e+1];
end
if nargout > 6
    x0 = [1.172640855235046e-2;4.226654570536448e-2;1.172641890535929e-2;4.226654570536448e-2;0.0;0.0;0.0;0.0];
end
if nargout > 7
    noise = [1.0./1.0e+2;1.0./5.0e+1];
end
if nargout > 8
    u0 = [5.176504417836309e-2;0.0];
end
end
