function out1 = inertiaSimulation(in1,payload)
%inertiaSimulation
%    OUT1 = inertiaSimulation(IN1,PAYLOAD)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:09

out1 = reshape([payload./4.0+3.3e+1./2.0e+1,0.0,0.0,2.31e+2./2.0e+2],[2,2]);
