function out1 = initialTauSimulation
%initialTauSimulation
%    OUT1 = initialTauSimulation

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:10

out1 = sqrt(2.0).*(9.81e+2./8.0e+1);
