function out1 = initialStateSimulation
%initialStateSimulation
%    OUT1 = initialStateSimulation

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:10

t2 = pi./4.0;
t3 = -t2;
out1 = [t3;t3-sqrt(2.0).*2.4525e-5];
