function out1 = inputToStateSimulation
%inputToStateSimulation
%    OUT1 = inputToStateSimulation

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:09

out1 = [0.0;0.0;0.0;1.0];
