controller:
  inner1:
    Kp: 25.0
    Ki: 2.0
    Kd: 0.0
  outer1:
    Kp: 5.0
    Ki: 0.0
    Kd: 0.0
  inner2:
    Kp: 10.0
    Ki: 1.0
    Kd: 0.0
  outer2:
    Kp: 5.0
    Ki: 0.0
    Kd: 0.0

model_parameters:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0


