function out1 = fkFcn(q1)
%fkFcn
%    OUT1 = fkFcn(Q1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    12-Feb-2024 17:10:22

t2 = cos(q1);
t3 = sin(q1);
out1 = reshape([t2,0.0,t3,0.0,-t3,0.0,t2,0.0,0.0,-1.0,0.0,0.0,t2,0.0,t3,1.0],[4,4]);
