function out1 = inertiaFcn(in1,in2)
%inertiaFcn
%    OUT1 = inertiaFcn(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:00

%dynamic parameters:   I1 I2 m1 m2 
I1 = in2(1,:);
I2 = in2(2,:);
m1 = in2(3,:);
m2 = in2(4,:);
q2 = in1(2,:);
t2 = cos(q2);
t3 = m2.*(9.0./1.6e+1);
out1 = reshape([I1+I2+m1.*(9.0./1.6e+1)+m2.*(4.5e+1./1.6e+1)+m2.*t2.*(9.0./4.0),I2+t3+m2.*t2.*(9.0./8.0),I2+m2.*(t2.*(3.0./2.0)+3.0./4.0).*(3.0./4.0),I2+t3],[2,2]);
