function out1 = jacobDotFcn(in1,in2)
%jacobDotFcn
%    OUT1 = jacobDotFcn(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:01

Dq1 = in2(1,:);
Dq2 = in2(2,:);
q1 = in1(1,:);
q2 = in1(2,:);
t2 = q1+q2;
t3 = Dq1+Dq2;
t6 = Dq1.*(3.0./2.0);
t7 = Dq2.*(3.0./2.0);
t4 = cos(t2);
t5 = sin(t2);
t8 = t6+t7;
out1 = [-Dq1.*(t4.*t8+t6.*cos(q1))-Dq2.*t3.*t4.*(3.0./2.0);-Dq1.*(t5.*t8+t6.*sin(q1))-Dq2.*t3.*t5.*(3.0./2.0);0.0;0.0;0.0;0.0];
