function regressor = regressorFcn(in1,in2,in3)
%regressorFcn
%    REGRESSOR = regressorFcn(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:00

%dynamic parameters:   I1 I2 m1 m2 
DDq1 = in3(1,:);
DDq2 = in3(2,:);
Dq1 = in2(1,:);
Dq2 = in2(2,:);
q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q2);
t5 = q1+q2;
t6 = DDq1+DDq2;
t8 = DDq1.*(9.0./1.6e+1);
t9 = DDq2.*(9.0./1.6e+1);
t7 = cos(t5);
t10 = t7.*7.3575;
regressor = reshape([DDq1,0.0,t6,t6,t2.*7.3575+t8,0.0,DDq1.*(4.5e+1./1.6e+1)+t2.*1.4715e+1+t9+t10+DDq1.*t3.*(9.0./4.0)+DDq2.*t3.*(9.0./8.0)-Dq2.^2.*t4.*(9.0./8.0)-Dq1.*Dq2.*t4.*(9.0./4.0),t8+t9+t10+DDq1.*t3.*(9.0./8.0)+Dq1.^2.*t4.*(9.0./8.0)],[2,4]);
