function out1 = inertiaFcn(in1,in2)
%inertiaFcn
%    OUT1 = inertiaFcn(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:34

%dynamic parameters:   I1 I2 I3 m1 m2 m3 
I1 = in2(1,:);
I3 = in2(3,:);
m1 = in2(4,:);
m2 = in2(5,:);
m3 = in2(6,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q2);
t3 = cos(q3);
t4 = sin(q2);
t5 = sin(q3);
t7 = m3./4.0;
t8 = m2./1.6e+1;
t6 = t3.^2;
t9 = t2.*t7;
t10 = t3.*t7;
t11 = (m2.*t2)./8.0;
t13 = (m3.*t2.*t3)./8.0;
t14 = (m3.*t4.*t5)./8.0;
t12 = (m3.*t6)./1.6e+1;
t15 = -t14;
t16 = t7+t8+t9+t10+t11+t12+t13;
out1 = reshape([I1+m1./1.6e+1+m2.*(5.0./1.6e+1)+m3./2.0+t10+t12+(m2.*t2)./4.0+(m3.*t2)./2.0+t3.*t9,t16,t15,t16,t7+t8+t10+t12,0.0,t15,0.0,I3+m3./1.6e+1],[3,3]);
