function out1 = jacobFcn(in1)
%jacobFcn
%    OUT1 = jacobFcn(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:36

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = q1+q2;
t9 = cos(t8);
t10 = sin(t8);
t11 = t4./2.0;
t12 = t11+1.0./2.0;
out1 = reshape([t5.*(-1.0./2.0)-(t2.*t6)./2.0-(t3.*t5)./2.0-(t2.*t4.*t6)./2.0-(t3.*t4.*t5)./2.0,0.0,t2./2.0+(t2.*t3)./2.0-(t5.*t6)./2.0-(t4.*t5.*t6)./2.0+t2.*t3.*t11,0.0,-1.0,0.0,-t10.*t12,0.0,t9.*t12,0.0,-1.0,0.0,t7.*t9.*(-1.0./2.0),-t11,t7.*t10.*(-1.0./2.0),t10,0.0,-t9],[6,3]);
