function regressor = regressorFcn(in1,in2,in3)
%regressorFcn
%    REGRESSOR = regressorFcn(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:24:34

%dynamic parameters:   I1 I2 I3 m1 m2 m3 
DDq1 = in3(1,:);
DDq2 = in3(2,:);
DDq3 = in3(3,:);
Dq1 = in2(1,:);
Dq2 = in2(2,:);
Dq3 = in2(3,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = q1+q2;
t9 = Dq1.^2;
t10 = Dq2.^2;
t11 = q3.*2.0;
t12 = Dq1+Dq2;
t16 = DDq1./2.0;
t17 = DDq2./4.0;
t18 = DDq1./1.6e+1;
t19 = DDq2./1.6e+1;
t13 = t4.^2;
t14 = sin(t11);
t15 = cos(t8);
t20 = (DDq1.*t3)./4.0;
t21 = (DDq1.*t4)./4.0;
t22 = t4.*t17;
t23 = (Dq1.*Dq3.*t7)./4.0;
t24 = (Dq2.*Dq3.*t7)./4.0;
t31 = t2.*(9.81e+2./2.0e+2);
t36 = t5.*t6.*(9.81e+2./2.0e+2);
t38 = t2.*t3.*t4.*(9.81e+2./4.0e+2);
t39 = t4.*t5.*t6.*(9.81e+2./4.0e+2);
t25 = -t23;
t26 = -t24;
t27 = t13.*t18;
t28 = t13.*t19;
t29 = (Dq1.*Dq3.*t14)./1.6e+1;
t30 = (Dq2.*Dq3.*t14)./1.6e+1;
t34 = t15.*(9.81e+2./4.0e+2);
t35 = t3.*t31;
t37 = -t36;
t40 = -t39;
t32 = -t29;
t33 = -t30;
mt1 = [DDq1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DDq3,t2.*(9.81e+2./4.0e+2)+t18,0.0,0.0,DDq1.*(5.0./1.6e+1)+t19+t20+t31+t34+(DDq2.*t3)./8.0-(t6.*t10)./8.0-(Dq1.*Dq2.*t6)./4.0,t18+t19+t34+(DDq1.*t3)./8.0+(t6.*t9)./8.0,0.0,t16+t17+t21+t22+t25+t26+t27+t28+t31+t32+t33+t35+t37+t38+t40-(t6.*t10)./4.0+t3.*t16+t3.*t17+t4.*t20-(Dq1.*Dq2.*t6)./2.0+(DDq2.*t3.*t4)./8.0-(DDq3.*t6.*t7)./8.0-(t4.*t6.*t10)./8.0-(Dq3.^2.*t4.*t6)./8.0-(Dq1.*Dq2.*t4.*t6)./4.0-(Dq1.*Dq3.*t3.*t7)./4.0-(Dq2.*Dq3.*t3.*t7)./4.0];
mt2 = [DDq1./4.0+t17+t20+t21+t22+t25+t26+t27+t28+t32+t33+t35+t37+t38+t40+(t6.*t9)./4.0+(DDq1.*t3.*t4)./8.0+(t4.*t6.*t9)./8.0,DDq3./1.6e+1-(t7.*(t6.*(t2.*(9.81e+2./1.0e+2)+t16)-t12.*(Dq1./2.0+Dq2./2.0)+t3.*(t5.*(9.81e+2./1.0e+2)-t9./2.0)))./4.0+(t12.^2.*t14)./3.2e+1];
regressor = reshape([mt1,mt2],3,6);
