function out1 = fkFcn(in1)
%fkFcn
%    OUT1 = fkFcn(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    12-Feb-2024 17:10:34

q1 = in1(1,:);
q2 = in1(2,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
out1 = reshape([t3,0.0,t4,0.0,-t4,0.0,t3,0.0,0.0,-1.0,0.0,0.0,t3.*(3.0./2.0)+cos(q1).*(3.0./2.0),0.0,t4.*(3.0./2.0)+sin(q1).*(3.0./2.0),1.0],[4,4]);
