function out1 = ikinFcn(x,y)
%ikineRigid
%    OUT1 = ikineRigid(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Feb-2024 14:57:56

t2 = x.*3.0;
t3 = x.^2;
t5 = y.*3.0;
t6 = y.^2;
t4 = t3.^2;
t7 = t6.^2;
t9 = t3.*9.0;
t11 = t6.*9.0;
t12 = t3+t6;
t13 = t3.*t6.*2.0;
t8 = -t4;
t10 = -t7;
t14 = -t13;
t15 = t12-9.0;
t16 = 1.0./t12;
t17 = t2+t12;
t18 = 1.0./t17;
t19 = t12.*t15;
t22 = t8+t9+t10+t11+t14;
t20 = -t19;
t26 = sqrt(t22);
t21 = sqrt(t20);
t23 = t16.*t21;
t24 = atan(t23);
t25 = t24.*2.0;
out1 = reshape([atan(t18.*(t5+t26)).*2.0,-t25,atan(t18.*(t5-t26)).*2.0,t25],[2,2]);
