function out1 = jacobFcn(in1)
%jacobFcn
%    OUT1 = jacobFcn(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    12-Feb-2024 17:10:35

q1 = in1(1,:);
q2 = in1(2,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = t3.*(3.0./2.0);
t6 = t4.*(3.0./2.0);
t7 = -t6;
out1 = reshape([t7-sin(q1).*(3.0./2.0),0.0,t5+cos(q1).*(3.0./2.0),0.0,-1.0,0.0,t7,0.0,t5,0.0,-1.0,0.0],[6,2]);
