function out1 = controlledJointSimulation
%controlledJointSimulation
%    OUT1 = controlledJointSimulation

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:23:56

out1 = reshape([0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,2]);
