function out1 = fkSimulation(in1)
%fkSimulation
%    OUT1 = fkSimulation(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:23:57

ql1 = in1(1,:);
ql2 = in1(2,:);
t2 = ql1+ql2;
t3 = cos(t2);
t4 = sin(t2);
out1 = reshape([t3,0.0,t4,0.0,-t4,0.0,t3,0.0,0.0,-1.0,0.0,0.0,t3.*(3.0./2.0)+cos(ql1).*(3.0./2.0),0.0,t4.*(3.0./2.0)+sin(ql1).*(3.0./2.0),1.0],[4,4]);
