function out1 = initialTauSimulation
%initialTauSimulation
%    OUT1 = initialTauSimulation

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:23:57

out1 = [2.50155e+2;0.0];
