function out1 = initialStateSimulation
%initialStateSimulation
%    OUT1 = initialStateSimulation

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:23:56

t2 = pi./2.0;
out1 = [0.0;t2;-5.0031e-5;t2];
