function out1 = inverseDynamicsNonLinearFcn(in1,in2,payload)
%inverseDynamicsNonLinearFcn
%    OUT1 = inverseDynamicsNonLinearFcn(IN1,IN2,PAYLOAD)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:23:56

Dql1 = in2(1,:);
Dql2 = in2(2,:);
Dqm1 = in2(3,:);
Dqm2 = in2(4,:);
ql1 = in1(1,:);
ql2 = in1(2,:);
qm1 = in1(3,:);
qm2 = in1(4,:);
t2 = cos(ql1);
t3 = sin(ql2);
t4 = ql1+ql2;
t5 = Dql2.^2;
t7 = Dql1.*2.0e+3;
t8 = Dql2.*2.1e+3;
t9 = ql2.*4.0e+6;
t10 = qm2.*4.0e+6;
t11 = ql1.*5.0e+6;
t12 = qm1.*5.0e+6;
t6 = cos(t4);
out1 = [Dqm1.*-2.0e+3+t2.*2.50155e+2+t6.*8.829e+1+t7+t11-t12+payload.*t2.*1.4715e+1+payload.*t6.*7.3575-t3.*t5.*(2.7e+1./2.0)-Dql1.*Dql2.*t3.*2.7e+1-payload.*t3.*t5.*(9.0./8.0)-Dql1.*Dql2.*payload.*t3.*(9.0./4.0);Dqm2.*-2.1e+3+t8+t9-t10+(payload.*(3.0./4.0)+9.0).*(t6.*(9.81e+2./1.0e+2)+Dql1.^2.*t3.*(3.0./2.0));Dqm1.*2.003e+3-t7-t11+t12+tanh(Dqm1.*1.0e+2).*5.0;Dqm2.*2.103e+3-t8-t9+t10+tanh(Dqm2.*1.0e+2).*5.0];
