function out1 = uMaxSimulation
%uMaxSimulation
%    OUT1 = uMaxSimulation

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    16-Feb-2024 13:23:56

out1 = [5.4e+3;2.4e+3];
