name: CI Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: true

      - name: Create Conda Environment and Install Dependencies
        run: |
          conda create -n labauto python=3.11 -y
          conda install -n labauto -y conda-forge::mujoco-python
          conda install -n labauto -y -c conda-forge pinocchio
          conda install -n labauto -y pyyaml
          conda install -n labauto -y main::aiohttp-jinja2
          conda install -n labauto -y plotly
          conda install -n labauto -y pytest scipy numpy

      - name: Run Tests Notch
        run: conda run -n labauto pytest labauto_pytest/test_notch_filter.py

      - name: Run Tests FIR
        run: conda run -n labauto pytest labauto_pytest/test_fir_filter.py

      - name: Run Tests LP
        run: conda run -n labauto pytest labauto_pytest/test_low_pass_filter.py

      - name: Run Delay
        run: conda run -n labauto pytest labauto_pytest/test_delay.py

      - name: Run PID
        run: conda run -n labauto pytest labauto_pytest/test_pid_controller.py
