name: CI Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest scipy numpy pin

      - name: Run Tests Notch
        run: pytest labauto_pytest/test_notch_filter.py
      - name: Run Tests FIR
        run: pytest labauto_pytest/test_fir_filter.py
      - name: Run Tests LP
        run: pytest labauto_pytest/test_low_pass_filter.py
      - name: Run Delay
        run: pytest labauto_pytest/test_delay.py
      - name: Run PID
        run: pytest labauto_pytest/test_pid_controller.py
